// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIctlJZqv_6Krfig6G2NyHFaw2onhskOg',
    appId: '1:171236072860:web:54f62f44cc11b92e943c59',
    messagingSenderId: '171236072860',
    projectId: 'smacchiatoria-579ca',
    authDomain: 'smacchiatoria-579ca.firebaseapp.com',
    storageBucket: 'smacchiatoria-579ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfKCiTaw1WlC6j-TWgnbYMEEYrhSEpe6A',
    appId: '1:171236072860:android:7a647189fada906d943c59',
    messagingSenderId: '171236072860',
    projectId: 'smacchiatoria-579ca',
    storageBucket: 'smacchiatoria-579ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgwWgbl94b36blRkneRId1aqwtbrDxwdQ',
    appId: '1:171236072860:ios:93bbfd3c6b637227943c59',
    messagingSenderId: '171236072860',
    projectId: 'smacchiatoria-579ca',
    storageBucket: 'smacchiatoria-579ca.firebasestorage.app',
    iosBundleId: 'com.example.forrealeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgwWgbl94b36blRkneRId1aqwtbrDxwdQ',
    appId: '1:171236072860:ios:93bbfd3c6b637227943c59',
    messagingSenderId: '171236072860',
    projectId: 'smacchiatoria-579ca',
    storageBucket: 'smacchiatoria-579ca.firebasestorage.app',
    iosBundleId: 'com.example.forrealeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIctlJZqv_6Krfig6G2NyHFaw2onhskOg',
    appId: '1:171236072860:web:e4f2b395a86de08a943c59',
    messagingSenderId: '171236072860',
    projectId: 'smacchiatoria-579ca',
    authDomain: 'smacchiatoria-579ca.firebaseapp.com',
    storageBucket: 'smacchiatoria-579ca.firebasestorage.app',
  );
}
